name: test-eks-python
on:
  # schedule:
  #   - cron: '*/15 * * * *' # run the workflow every 15 minutes
  workflow_dispatch: # be able to run the workflow on demand

permissions:
  id-token: write
  contents: read

jobs:
  e2e-test:
    strategy:
      fail-fast: false
      matrix:
        aws-region: ['us-east-1']
    uses: ./.github/workflows/appsignals-python-e2e-eks-test.yml
    secrets: inherit
    with:
      aws-region: ${{ matrix.aws-region }}
      test-cluster-name: 'e2e-canary-test-python'
      caller-workflow-name: 'test-eks-python'
      application-signals-adot-image: public.ecr.aws/aws-observability/adot-autoinstrumentation-python
      application-signals-adot-image-tag: v0.0.1