name: Validate E2E Tests Are Accounted For
on:
  workflow_call:

env:
  TEST_RESOURCES_FOLDER: ${GITHUB_WORKSPACE}

jobs:
  validate-e2e-tests-are-accounted-for:
    runs-on: ubuntu-latest
    steps:
      - name: Install Ruby
        uses: ruby/setup-ruby@v1.221.0
        with:
          ruby-version: "3.4"
      - name: Get workflow files for Java
        if: contains(github.repository, 'aws-otel-java-instrumentation')
        run: |
          cd ${{ env.TEST_RESOURCES_FOLDER }}
          git clone https://github.com/jj22ee/aws-application-signals-test-framework.git
          cd aws-application-signals-test-framework/.github/workflows/

          # Get all test workflow files that should be used by ADOT Java
          echo "TESTS_USED=$(ls | grep -E '(^java-)|(^metric-limiter-)' | grep -Ev '(lambda-layer-perf-test|otlp-ocb)' | grep -E 'test\.ya?ml$' | sort | tr '\n' ' ' | sed 's/ $//')" >> $GITHUB_ENV

          cd ${{ env.TEST_RESOURCES_FOLDER }}
          git clone -b ${{ github.ref_name }} https://github.com/jj22ee/aws-otel-java-instrumentation.git
          cd aws-otel-java-instrumentation/.github/workflows/

          # Get all test framework workflows actually used in application-signals-e2e-test.yml
          echo "TESTS_AVAILABLE=$(ruby -ryaml -e 'puts YAML.load_file("application-signals-e2e-test.yml")["jobs"].values \
              .map { |v| v["uses"] } \
              .compact \
              .uniq \
              .select { |u| u.include?("aws-application-signals-test-framework/.github/workflows") && !u.include?("validate-e2e-tests-are-accounted-for") } \
              .map { |u| u.split("/").last.split("@").first } \
              .sort \
              .join(" ")')" >> $GITHUB_ENV

      - name: Get workflow files for JavaScript
        if: contains(github.repository, 'aws-otel-js-instrumentation')
        run: |
          cd ${{ env.TEST_RESOURCES_FOLDER }}
          git clone https://github.com/jj22ee/aws-application-signals-test-framework.git
          cd aws-application-signals-test-framework/.github/workflows/

          # Get all test workflow files that should be used by ADOT JavaScript
          echo "TESTS_USED=$(ls | grep -E '^node-' | grep -v 'lambda-layer-perf-test' | grep -E 'test\.ya?ml$' | sort | tr '\n' ' ' | sed 's/ $//')" >> $GITHUB_ENV

          cd ${{ env.TEST_RESOURCES_FOLDER }}
          git clone -b ${{ github.ref_name }} https://github.com/jj22ee/aws-otel-js-instrumentation.git
          cd aws-otel-js-instrumentation/.github/workflows/

          # Get all test framework workflows actually used in application-signals-e2e-test.yml
          echo "TESTS_AVAILABLE=$(ruby -ryaml -e 'puts YAML.load_file("application-signals-e2e-test.yml")["jobs"].values \
              .map { |v| v["uses"] } \
              .compact \
              .uniq \
              .select { |u| u.include?("aws-application-signals-test-framework/.github/workflows") && !u.include?("validate-e2e-tests-are-accounted-for") } \
              .map { |u| u.split("/").last.split("@").first } \
              .sort \
              .join(" ")')" >> $GITHUB_ENV

      - name: Get workflow files for Python
        if: contains(github.repository, 'aws-otel-python-instrumentation')
        run: |
          cd ${{ env.TEST_RESOURCES_FOLDER }}
          git clone https://github.com/jj22ee/aws-application-signals-test-framework.git
          cd aws-application-signals-test-framework/.github/workflows/

          # Get all test workflow files that should be used by ADOT Python
          echo "TESTS_USED=$(ls | grep -E '^python-' | grep -v 'lambda-layer-perf-test' | grep -E 'test\.ya?ml$' | sort | tr '\n' ' ' | sed 's/ $//')" >> $GITHUB_ENV

          cd ${{ env.TEST_RESOURCES_FOLDER }}
          git clone -b ${{ github.ref_name }} https://github.com/jj22ee/aws-otel-python-instrumentation.git
          cd aws-otel-python-instrumentation/.github/workflows/

          # Get all test framework workflows actually used in application-signals-e2e-test.yml
          echo "TESTS_AVAILABLE=$(ruby -ryaml -e 'puts YAML.load_file("application-signals-e2e-test.yml")["jobs"].values \
              .map { |v| v["uses"] } \
              .compact \
              .uniq \
              .select { |u| u.include?("aws-application-signals-test-framework/.github/workflows") && !u.include?("validate-e2e-tests-are-accounted-for") } \
              .map { |u| u.split("/").last.split("@").first } \
              .sort \
              .join(" ")')" >> $GITHUB_ENV

      - name: Get workflow files for .NET
        if: contains(github.repository, 'aws-otel-dotnet-instrumentation')
        run: |
          cd ${{ env.TEST_RESOURCES_FOLDER }}
          git clone https://github.com/jj22ee/aws-application-signals-test-framework.git
          cd aws-application-signals-test-framework/.github/workflows/

          # Get all test workflow files that should be used by ADOT .NET
          echo "TESTS_USED=$(ls | grep -E '^dotnet-' | grep -v 'lambda-layer-perf-test' | grep -E 'test\.ya?ml$' | sort | tr '\n' ' ' | sed 's/ $//')" >> $GITHUB_ENV

          cd ${{ env.TEST_RESOURCES_FOLDER }}
          git clone -b ${{ github.ref_name }} https://github.com/jj22ee/aws-otel-dotnet-instrumentation.git
          cd aws-otel-dotnet-instrumentation/.github/workflows/

          # Get all test framework workflows actually used in application-signals-e2e-test.yml
          echo "TESTS_AVAILABLE=$(ruby -ryaml -e 'puts YAML.load_file("application-signals-e2e-test.yml")["jobs"].values \
              .map { |v| v["uses"] } \
              .compact \
              .uniq \
              .select { |u| u.include?("aws-application-signals-test-framework/.github/workflows") && !u.include?("validate-e2e-tests-are-accounted-for") } \
              .map { |u| u.split("/").last.split("@").first } \
              .sort \
              .join(" ")')" >> $GITHUB_ENV

      - name: Get workflow files for CloudWatch Agent
        if: contains(github.repository, 'amazon-cloudwatch-agent')
        run: |
          cd ${{ env.TEST_RESOURCES_FOLDER }}
          git clone https://github.com/jj22ee/aws-application-signals-test-framework.git
          cd aws-application-signals-test-framework/.github/workflows/

          # Get all test workflow files that should be used by CloudWatch Agent
          echo "TESTS_USED=$(ls | grep -E '(^java-)|(^node-)|(^python-)|(^dotnet-)|(^metric-limiter-)' | grep -Ev '(sigv4|lambda-test|lambda-layer-perf-test|ocb|genesis)' | grep -E 'test\.ya?ml$' | sort | tr '\n' ' ' | sed 's/ $//')" >> $GITHUB_ENV

          cd ${{ env.TEST_RESOURCES_FOLDER }}
          git clone -b ${{ github.ref_name }} https://github.com/jj22ee/amazon-cloudwatch-agent.git
          cd amazon-cloudwatch-agent/.github/workflows/

          # Get all test framework workflows actually used in application-signals-e2e-test.yml
          echo "TESTS_AVAILABLE=$(ruby -ryaml -e 'puts YAML.load_file("application-signals-e2e-test.yml")["jobs"].values \
              .map { |v| v["uses"] } \
              .compact \
              .uniq \
              .select { |u| u.include?("aws-application-signals-test-framework/.github/workflows") && !u.include?("validate-e2e-tests-are-accounted-for") } \
              .map { |u| u.split("/").last.split("@").first } \
              .sort \
              .join(" ")')" >> $GITHUB_ENV

      - name: Compare TESTS_USED and TESTS_AVAILABLE
        run: |
          echo "Expected: $TESTS_USED"
          echo "Actual: $TESTS_AVAILABLE"
          if [[ -z "$TESTS_USED" || -z "$TESTS_AVAILABLE" || "$TESTS_USED" != "$TESTS_AVAILABLE" ]]; then
            echo "Mismatch found!"
            exit 1
          fi