name: Validate E2E Tests Are Accounted For
on:
  workflow_call:
    inputs:
      exclusions:
        description: 'Comma-separated list of test files to exclude from validation'
        type: string
        required: false
        default: ''

env:
  TEST_RESOURCES_FOLDER: ${GITHUB_WORKSPACE}

jobs:
  validate-e2e-tests-are-accounted-for:
    runs-on: ubuntu-latest
    steps:
      - name: Install Ruby
        uses: ruby/setup-ruby@v1.221.0
        with:
          ruby-version: "3.4"

      - name: Determine workflow files expected to be used by ADOT Java
        if: contains(github.repository, 'aws-otel-java-instrumentation')
        run: |
          cd ${{ env.TEST_RESOURCES_FOLDER }}
          git clone https://github.com/jj22ee/aws-application-signals-test-framework.git
          cd aws-application-signals-test-framework/.github/workflows/

          # Get all test workflow files that should be used by ADOT Java, applying exclusions
          EXCLUSIONS="${{ inputs.exclusions }}"
          [[ -n "$EXCLUSIONS" ]] && echo "Applying exclusions to TESTS_EXPECTED: $EXCLUSIONS"
          echo "TESTS_EXPECTED=$(ls | grep -E '(^java-)|(^metric-limiter-)' | grep -Ev '(lambda-layer-perf-test|otlp-ocb)' | grep -E 'test\.ya?ml$' | { [[ -n "$EXCLUSIONS" ]] && grep -v -F -f <(echo "$EXCLUSIONS" | tr ',' '\n') || cat; } | sort | tr '\n' ' ' | sed 's/ $//')" >> $GITHUB_ENV

      - name: Determine workflow files expected to be used by ADOT JavaScript
        if: contains(github.repository, 'aws-otel-js-instrumentation')
        run: |
          cd ${{ env.TEST_RESOURCES_FOLDER }}
          git clone https://github.com/jj22ee/aws-application-signals-test-framework.git
          cd aws-application-signals-test-framework/.github/workflows/

          # Get all test workflow files that should be used by ADOT JavaScript, applying exclusions
          EXCLUSIONS="${{ inputs.exclusions }}"
          [[ -n "$EXCLUSIONS" ]] && echo "Applying exclusions to TESTS_EXPECTED: $EXCLUSIONS"
          echo "TESTS_EXPECTED=$(ls | grep -E '^node-' | grep -v 'lambda-layer-perf-test' | grep -E 'test\.ya?ml$' | { [[ -n "$EXCLUSIONS" ]] && grep -v -F -f <(echo "$EXCLUSIONS" | tr ',' '\n') || cat; } | sort | tr '\n' ' ' | sed 's/ $//')" >> $GITHUB_ENV

      - name: Determine workflow files expected to be used by ADOT Python
        if: contains(github.repository, 'aws-otel-python-instrumentation')
        run: |
          cd ${{ env.TEST_RESOURCES_FOLDER }}
          git clone https://github.com/jj22ee/aws-application-signals-test-framework.git
          cd aws-application-signals-test-framework/.github/workflows/

          # Get all test workflow files that should be used by ADOT Python, applying exclusions
          EXCLUSIONS="${{ inputs.exclusions }}"
          [[ -n "$EXCLUSIONS" ]] && echo "Applying exclusions to TESTS_EXPECTED: $EXCLUSIONS"
          echo "TESTS_EXPECTED=$(ls | grep -E '^python-' | grep -v 'lambda-layer-perf-test' | grep -E 'test\.ya?ml$' | { [[ -n "$EXCLUSIONS" ]] && grep -v -F -f <(echo "$EXCLUSIONS" | tr ',' '\n') || cat; } | sort | tr '\n' ' ' | sed 's/ $//')" >> $GITHUB_ENV

      - name: Determine workflow files expected to be used by ADOT .NET
        if: contains(github.repository, 'aws-otel-dotnet-instrumentation')
        run: |
          cd ${{ env.TEST_RESOURCES_FOLDER }}
          git clone https://github.com/jj22ee/aws-application-signals-test-framework.git
          cd aws-application-signals-test-framework/.github/workflows/

          # Get all test workflow files that should be used by ADOT .NET, applying exclusions
          EXCLUSIONS="${{ inputs.exclusions }}"
          [[ -n "$EXCLUSIONS" ]] && echo "Applying exclusions to TESTS_EXPECTED: $EXCLUSIONS"
          echo "TESTS_EXPECTED=$(ls | grep -E '^dotnet-' | grep -v 'lambda-layer-perf-test' | grep -E 'test\.ya?ml$' | { [[ -n "$EXCLUSIONS" ]] && grep -v -F -f <(echo "$EXCLUSIONS" | tr ',' '\n') || cat; } | sort | tr '\n' ' ' | sed 's/ $//')" >> $GITHUB_ENV

      - name: Determine workflow files expected to be used by CloudWatch Agent
        if: contains(github.repository, 'amazon-cloudwatch-agent')
        run: |
          cd ${{ env.TEST_RESOURCES_FOLDER }}
          git clone https://github.com/jj22ee/aws-application-signals-test-framework.git
          cd aws-application-signals-test-framework/.github/workflows/

          # Get all test workflow files that should be used by CloudWatch Agent, applying exclusions
          EXCLUSIONS="${{ inputs.exclusions }}"
          [[ -n "$EXCLUSIONS" ]] && echo "Applying exclusions to TESTS_EXPECTED: $EXCLUSIONS"
          echo "TESTS_EXPECTED=$(ls | grep -E '(^java-)|(^node-)|(^python-)|(^dotnet-)|(^metric-limiter-)' | grep -Ev '(sigv4|lambda-test|lambda-layer-perf-test|ocb|genesis)' | grep -E 'test\.ya?ml$' | { [[ -n "$EXCLUSIONS" ]] && grep -v -F -f <(echo "$EXCLUSIONS" | tr ',' '\n') || cat; } | sort | tr '\n' ' ' | sed 's/ $//')" >> $GITHUB_ENV

      - name: Determine workflow files actually being used by ${{ github.repository }}
        run: |
          cd ${{ env.TEST_RESOURCES_FOLDER }}
          git clone -b ${{ github.ref_name }} https://github.com/${{ github.repository }}.git ${{ github.repository }}
          cd ${{ github.repository }}/.github/workflows/

          # Get all test framework workflows actually used in application-signals-e2e-test.yml
          echo "TESTS_ACTUALLY_USED=$(ruby -ryaml -e 'puts YAML.load_file("application-signals-e2e-test.yml")["jobs"].values \
              .map { |v| v["uses"] } \
              .compact \
              .uniq \
              .select { |u| u.include?("aws-application-signals-test-framework/.github/workflows") && !u.include?("validate-e2e-tests-are-accounted-for") } \
              .map { |u| u.split("/").last.split("@").first } \
              .sort \
              .join(" ")')" >> $GITHUB_ENV

      - name: Compare TESTS_ACTUALLY_USED and TESTS_EXPECTED
        run: |
          echo "Tests being used: $TESTS_ACTUALLY_USED"
          echo "Tests expected to be used: $TESTS_EXPECTED"
          if [[ -z "$TESTS_ACTUALLY_USED" || -z "$TESTS_EXPECTED" || "$TESTS_ACTUALLY_USED" != "$TESTS_EXPECTED" ]]; then
            echo "Mismatch found!"
            exit 1
          fi
